export enum RoomStatusEnum {
  RENTING = 'RENTING',
  BOOKING = 'BOOKING',
  EMPTY = 'EMPTY',
  DIRTY = 'DIRTY',
  REPAIRING = 'REPAIRING',
  CLEANING = 'CLEANING',
  PAYMENT_OF_DATE = 'PAYMENT_OF_DATE',
  EXPIRED = 'EXPIRED',
}
